### PR TITLE
moving federal crop insurance corp. right

### PR DESCRIPTION
**Pull request by gbinal**

### CODE REVIEW

**Comment by JoshData** [comment]
I think I just gave you permission to commit/merge here, @gbinal . If that worked (I still don't understand github permissions; cc @benbalter !), go ahead and merge away!

**Comment by gbinal** [comment]
Great, thanks!

**Comment by konklone** [comment]
Are #7 and #8 here the first PRs we've merged into @unitedstates from government employees (in that capacity)?

**Comment by JoshData** [comment]
Seems like it's the first federal govt employee commit, at least as far as I can remember too. Gov-wide @vzvenyach has @gbinal beat in https://github.com/unitedstates/authentication/commit/868f68168e3a1f5e17abb71a032194e5eb6fe577 (if not earlier).

**Comment by gbinal** [comment]
image

image

**Comment by JoshData** [comment]
Well played. 

On June 23, 2014 8:15:15 PM EDT, Gray Brooks notifications@github.com wrote:

> image
> 
> image
> 
> image
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/unitedstates/orgchart/pull/8#issuecomment-46918269

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Pull request merged**
